all: false
dir: 'internal/mocks/{{.SrcPackageName}}'
filename: '{{.InterfaceName}}.go'
force-file-write: true
formatter: goimports
structname: '{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
template: testify
packages:
  github.com/lovelaze/nebula-sync:
    config:
      all: true
      recursive: true
